name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo "go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> "$GITHUB_OUTPUT"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Build geoip
        id: build
        env:
          GEOIP_TOKEN: ${{ secrets.GEOIP_REPO_TOKEN }}
        run: go run -v .
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          mkdir dist
          sha256sum geoip.db > dist/geoip.db.sha256sum
          sha256sum geoip-cn.db > dist/geoip-cn.db.sha256sum
          cp geoip.db* dist/
          cp geoip-cn.db* dist/
          
      - name: Push artifacts to release branch
        if: steps.build.outputs.skip != 'true'
        run: |
          git config --local user.email "${{ vars.OWNER_EMAIL }}"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          git checkout --orphan release-orphan
          git rm -rf .
          
          cp dist/* .
          git add geoip.db
          git add geoip-cn.db
          git add geoip.db.sha256sum
          git add geoip-cn.db.sha256sum
          
          git commit -am "Updated at $(date)"
          git branch -D release
          git branch -m release
          
          git remote add myrepo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git tag "${{ steps.build.outputs.tag }}"
          git push myrepo "${{ steps.build.outputs.tag }}"
          git push -f -u myrepo release

      - name: Purge CDN Cache
        if: steps.build.outputs.skip != 'true'
        run: |
          curl -L "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/" > /dev/null 2>&1

      - name: Release
        if: steps.build.outputs.skip != 'true'
        id: release
        uses: softprops/action-gh-release@v2.0.6 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          name: "${{ steps.build.outputs.tag }}"
          tag_name: "${{ steps.build.outputs.tag }}"
          files: |
            geoip.db
            geoip.db.sha256sum
            geoip-cn.db
            geoip-cn.db.sha256sum
